### ISSUE TITLE
New R Code Snippet Suggestions

### ISSUE THREAD

**Issue by brichard1638** [nanxstats/r-base-shortcuts#2]
There are so many programmatic capabilities and secrets in R that it remains to be seen whether any R developer who has no more than a fundamental knowledge of the tool's 31 baseline packages, commonly referred to as the tidyverse, would ever discover.

R currently maintains nearly 20,000 active packages on its network, called CRAN.

Consequently, I arguably possess one of the most extensive collections of R code snippets in the world. These code snippets are principally targeted to address challenges supporting Data Science proper, Software Engineering, Machine Learning, and Generative Art.

To that end, I have hundreds of R code snippets that I have either captured or developed over the last 8 years.

This repository is so large that I had to develop a separate database and code library to manage it.

While I had most of the code snippets that you posted in your R Short Cuts, there were a few items that I didn't have.

So, as a quid pro quo to the effort that you so kindly shared, I thought I would share a few of the code snippets and ideas that I have collected over the years with you and your audience.

This code will be provided under what I refer to as the "R-Insight" series under the "Issues" section of your GitHub repository.

It is my sincere hope that you decide to share them either in their original form, or redacted as you interpret them.

In terms of credibility as a viable source in this space, I wrote a book on R which was published in July 2021 titled, "Conquering R Basics." This work can be found on Amazon Books.

If you are interested in a particular topic or interest about which I earlier referenced, reach out as I most likely have an article or two that describes it. -BR

**Comment by nanxstats** [comment]
Thanks for the note. Contributions welcomed. Please see [contributing guide](https://github.com/nanxstats/r-base-shortcuts/blob/main/.github/CONTRIBUTING.md) for details.
