### ISSUE TITLE
R-Insight: Unique Identifiers

### ISSUE THREAD

**Issue by brichard1638** [nanxstats/r-base-shortcuts#5]
Unique Identifiers are important in data analysis. They are used to uniquely identify a record within a dataset. It may be necessary to create unique identifiers beyond the sequential order of traditional datasets in R where the numeric sequence begins with 1.

There are other ways to create unique, more complex identifiers but this solution provides an economy of code to achieve the task.

This code snippet showcases how to generate unique identifiers using two different methods:

This example uses R's ability to generate temporary file names as a means to extract and generate Unique Identifiers:
- Example 1:
  `library(easyr)`
  `x = right(replicate(basename(tempfile()), n = 5), 8)`

NOTE1: The n argument within the **replicate** function determines the number of Unique Identifiers to generate.

NOTE2: Using this method (Example 1), up to 8 characters can be used to create unique identifiers. The example generates 5, 8-digit results.

- Example 2:
  `library(wakefield)`
  `x =  string(n = 5, length = 8)`

The n argument determines the number of Unique Identifiers to generate and the length argument controls the number of characters comprising each Unique Identifier.

NOTE: Example 2 is superior to Example 1 in terms of flexibility because the identifier length can be customized. Example 1 provides Unique Identifiers that cannot exceed 8 characters in length.

**Comment by nanxstats** [comment]
I agree that unique identifiers are important in some use cases.

The point, though, is that the generation process should not be affected by the global random seed. To that end:

- For simplicity, I would just use [uuid](https://cran.r-project.org/package=uuid).
- [shiny](https://github.com/rstudio/shiny/blob/main/R/utils.R) has an implementation of `withPrivateSeed()` and custom identifier generators for marking the div elements.
