### ISSUE TITLE
R-Insight: Return a Listing of all Functions in a Target R Package

### ISSUE THREAD

**Issue by brichard1638** [nanxstats/r-base-shortcuts#7]
The R code in this snippet allows the user to directly write console output in RStudio to a pre-designated text file. The purpose of this code snippet is to provide an alternative for capturing R data results when such data cannot be stored within a data object. List object data produced by various R functions, for example, are very difficult to convert to data frames, which is necessary if the data needs to be externally accessed and used. The following R code resolves this issue:

This example returns a listing of all R package functions by name and by structure, converting the output to a text file:

`library(dplyr)`
`fp = paste0(path.expand("~"), "/dplyr_fcn_list.txt")`
`sink(fp, append = FALSE, split = FALSE)`
`lsf.str(pos = "package:dplyr")`
`sink()`
`closeAllConnections()`

NOTE1: Before executing the code, the target package must be **locally** installed **AND loaded.**

NOTE2: The **lst.str** function is an abbreviation for **List Functions as a String.**

**Comment by nanxstats** [comment]
Sure, there is a need to redirect the outputs at times.

I agree that the base R solution would involve `sink()` or `capture.output()`. There are also [`with_sink` facilities in withr](https://withr.r-lib.org/reference/with_sink.html).

It has nothing to do with dplyr or listing the function signatures from namespaces, though.
